language: rust
rust:
- stable
- beta
- nightly
branches:
  only:
  - master
  - travis-ci
  - "/^v.*$/"
os:
- linux
matrix:
  allow_failures:
  - rust: nightly
after_success: |
  [ $TRAVIS_OS_NAME = linux ] &&
  [ $TRAVIS_RUST_VERSION = stable ] &&
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  cargo doc --no-deps &&
  echo '<meta http-equiv=refresh content=0;url=rs-collector/index.html>' > target/doc/index.html &&
  pip install --user ghp-import &&
  /home/travis/.local/bin/ghp-import -n target/doc &&
  git push -fq https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
before_deploy:
- cd /home/travis/build/lukaspustina/rs-collector; cargo build --release
- cd /home/travis/build/lukaspustina; git clone https://github.com/lukaspustina/rs-collector-deb.git
- cd /home/travis/build/lukaspustina/rs-collector-deb; BIN_DIR=../rs-collector/target/release ARCH=amd64 VERSION=$TRAVIS_TAG TAG=$TRAVIS_TAG DIST=trusty make package
deploy:
  provider: packagecloud
  username: lukaspustina
  token:
    secure: aYbYmH2MTsUBTU7TlWTbKle1aFWZz+ALFejdr8tjSJ0VK45h7QtnsC1IDPuqraIV8NstB3wENZO5kHL3ENLyWDTXCMP/0TYlhlewQGGxlc4wB43jpe6SI4Y/fQDRUgk+2IdawOnri7Xntf650QzwTOUNYYw/OwqXwjVqaWg3Lh0o2RTp1kkS2c8sAVE+LgyUVgeWXdqonl/8katKutLf9GEui16SJ2swG+4t/hUq39MSJerqtFK2eFYXySxlcedwEmoVLQOLo428U4yxDAa2QXb0cTQSTg38KVwRmcQbhes0x2jFhDGFQLd+5AvEIRZqNKggWUWjbdv8S1qyZMqGgkIZSkIac4p1NN0tadv4Y8xt0HyvItxulvsNjcrwlVZmdkr1qfE7LVv6MNHf1YF9yjXVWEPyfZvW6PgJU5zT0PM0visckzJE5PzfkBNdxMfydkVi8y6UtFPcdfE+eG6SHzZlr2F888qe04n9KBwUBVFqtZo8jtuG4VxIam8Zizhh2sbQuEe993+EVcY1kNWvUNLmAgR5gTzXxP+5C4kjr8fi5TDegLLnqXy/h/KPMWrB0l9b74BBjkzC3VQOONPN6ZDCp1Wpb4rw11trS3+F/oPcg8zih7I21uyNZIiynjXai3EOpXAkTikCtMD+5NrinjizzXbqLPpHvkkik/Nt/FU=
  repository: opensource
  dist: ubuntu/trusty
  package_glob: "**/*.deb"
  skip_cleanup: true
  on:
    tags: true
    condition:
    - "$TRAVIS_OS_NAME == linux"
    - "$TRAVIS_RUST_VERSION == stable"
after_deploy:
- cd /home/travis/build/lukaspustina/rs-collector; cargo publish --token ${CRATES_IO_TOKEN}
env:
  global:
  - secure: QIuMZyJm4gxKGoXPcd8xb6DWOwHWXOnLRjddM1p/X1byatS2+37qMVJ3c4jsj8vCh2XC+0t1v+Vj61/+VdO4C7M6uPY7fcBMPwNdLzmkrJqyTtDGMSzM18FrJa1iQ3CPyD2JPbb568y3/lmKxmwBxiLBPX4d5GflrJF1leOSqs6Y8LdCYzQe8b+qyTJt5b2cscp6/5td7ObmIaxnbPjtAMdW99t09ljhz4OKtBCsQCM+VeiOT3QiNTO1rsM1yZbC8Qv5B84yhYiCO2QGM56SHBlQb8htpaVePu7RKeYU+SyE+EPR3xjjMcR0mlm6WkAetokNoK55gnb1Cd0KYUrhyAWMvJxvYSkFI5NMGUIgLm+grtKe/oyr5A9cM3SvAxAdKXjjl1CtLEYeoHotgH1pdsdSBtSx7n2W9ozMd2JjVGKu8+DlhW4lY2fgtXiKFqojSy9aislB4UDOE3yA/Audsq8C8pavUNwaS1H4I5bfJ98liv8ibgL5jl25OdbSzqc9crelIA3XWglj8Hc2jHdLx2QpHG4NdR0O/WX7/Ccw7wq1Z+GHCfdz86NUEOypnr+MTxPV7R1tsQBH8DAq7itx24EqNZkDoULmPiflDdc6o48Ns0GKBftdMSZ/YU+RGbVuybHieXGlnr/1gYzUMP30x2QIVvO19sTDv8BhXQOBV9M=
  - secure: UPnfo6hJKDnd+XuqIvCfj374N3PuBxxG3rK5NoEOnzBWcDxrZwkBxVL+IqJtwDl/OCbZlD1eNDHqdPkSgO0ph+6+tpnCe1KMU2vwwQAG9yCmysmomI7cGcCg8oCvrg76ADlE/UVU0HXIWZgCmlt77KK6gVpagfEiOYUm/ScBJPmJUs0JTgG3RjGRaU//FIJGAwJInSIMpoPHC5XfKdgEEj9426XsbWQcoFwk+InRN6qlnr1hORA7KFPhBkjcnRn1ky/IFYXqjgNwZgGfYyK37idESPZVRd+u+Q8CVHSXrKQRwGGsIb+RZsoigt3AcaAR6ttVssGIlsvLS5VUI3mkjLnQodIoY7EXPqpRAfGTL2TprVcler7NeSVv0FxfxDaAeOGwDDjS5pZ/aLLMydY4eAlCVU5CApNjO7cYHBSGIkIw6I4woCeqNhMPd+rZ7i7AOJds4X26MoFPjNQzOmBkNDYV0X6SjCmMVS2ih2KufVv5QhuZxDg5uJPTSQXjGmQ4YTIdJ+i3Rm3mtJQsN/uXKdI/E/h5o93X/CmaQdpGSjNms7O9r3TMshP9b0YwmNJk4P40BgKaTi/AdTqTplu7+gpDLfrKW1w57gCBiQ8IvMd5fajTQDPrQcebqRaa0EMnGmZnyREsxdsZYGfzgWzfeTRSgtcEAtqvu1z88jiR0SE=
